{% set name = "cached_interpolate" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cached_interpolate-{{ version }}.tar.gz
  sha256: a9320293a3106f11d2356657b89060863180d7fa600bd82112791e8aabc3a1c0

build:
  skip: true  # [py<39 or python_impl == 'pypy']
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy >=2                              # [build_platform != target_platform and python_impl == 'cpython']
    - numpy                                  # [build_platform != target_platform and python_impl == 'pypy']
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
    - setuptools
    - setuptools-scm
  run:
    - python

test:
  imports:
    - cached_interpolate
    - cached_interpolate.build
  commands:
    - pip check
    - pytest --pyargs cached_interpolate.test
  requires:
    - pip
    - pytest
    - scipy
    - jax                                    # [python_impl == 'cpython' and target_platform == "linux-64"]

about:
  home: https://github.com/ColmTalbot/cached_interpolation
  summary: Efficient repeated evaluation of splines at fixed points.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ColmTalbot
